Fix broken link
microsoft/electionguard pull request #38
Opened 2020-10-11 00:03 UTC by iHiD

There is a broken link in the README.md. It's in fact a missing link to GitHub pages.

I've changed it to point to the GitHub docs directory, until GitHub Pages is set up.

2020-10-12 12:23 UTC, keithrfung requested changes
Great find but wrong link.

`[GitHub Pages documentation](https://microsoft.github.io/electionguard)`

2020-10-12 12:46 UTC, iHiD commented on README.md
> +ElectionGuard is always improving. To keep up with the latest, check our **[docs on GitHub](https://github.com/microsoft/electionguard/blob/main/docs/index.md)**. For developers looking to get starte
```suggestion
ElectionGuard is always improving. To keep up with the latest, check our **[GitHub Pages documentation](https://microsoft.github.io/electionguard)**. For developers looking to get started, we recommend the following repositories.
```

2020-10-12 12:47 UTC, iHiD commented
@keithrfung Updated. Thanks. 

You ok to Squash when you merge, save me having to checkout the repo? 🙂 If you have that disabled for this repo, let me know and I'll sort it locally.

2020-10-21 14:24 UTC, keithrfung approved these changes

2020-10-21 14:24 UTC, merged